# Generated by Django 2.2.6 on 2019-11-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=54)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=127)),
                ('re_password', models.CharField(max_length=127)),
            ],
        ),
    ]
