# Generated by Django 2.2.6 on 2019-11-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_jo'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
